/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconSvg: typeof import('@imohuan-plus/components')['IconSvg']
    IInput: typeof import('@imohuan-plus/components')['IInput']
    ImColor: typeof import('@imohuan-plus/components')['ImColor']
    ImList: typeof import('@imohuan-plus/components')['ImList']
    IType: typeof import('@imohuan-plus/components')['IType']
  }
}
